#!/bin/bash

# Networking Lab - Mission List
echo "🕵️ Welcome to the Network Detective Lab!"
echo "----------------------------------------"
echo "Your mission, should you choose to accept it, is to gather intelligence on the following targets."
echo ""
echo "MISSION 1: The IP Address"
echo "Find the IP address of 'google.com' using the 'dig' or 'nslookup' command."
echo ""
echo "MISSION 2: The Latency"
echo "Check the response time (latency) of 'github.com'. How long does it take for a packet to return?"
echo "Hint: Use 'ping -c 4 github.com'"
echo ""
echo "MISSION 3: The Headers"
echo "Inspect the HTTP headers of 'https://www.wikipedia.org'. What web server are they using?"
echo "Hint: Use 'curl -I https://www.wikipedia.org'"
echo ""
echo "MISSION 4: The Local Port"
echo "List all the ports currently listening on your local machine."
echo "Hint: Use 'ss -tuln' or 'netstat -tuln'"
echo ""
echo "MISSION 5: The Traceroute"
echo "Trace the path your data takes to reach '8.8.8.8'. How many 'hops' does it take?"
echo "Hint: Use 'traceroute 8.8.8.8' (You might need to install it: sudo apt install traceroute)"
echo ""
echo "----------------------------------------"
echo "Once you have gathered your notes, run 'bash exercises/networking_verify.sh' to test your knowledge!"
